version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 6000:3000
    volumes:
      - ./:/usr/src/app
    tty: true
    networks:
      - sinatra-app

networks:
  sinatra-app:
